import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import style from '../styles/Admin.module.css'
import { Container } from 'react-bootstrap';


function Admin() {
    const [users, setUsers] = useState([])
    const [adminid, setAdminId] = useState('')

    const adminlogin = async adminid => {
        const s = process.env.BASE_FETCH_URL
        const res = await fetch(`/api/checkadmin/${adminid}`)
        const data = await res.json()
        setUsers(data)
        localStorage.setItem('user', data.name)
    }

    return (
        <>
            <Head>
                <title>Admin Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"/>
            </Head>
            <Container>
                <h1 className={style.mainTitle}>Admin Login</h1>
            </Container>
            <Container className={style.loginContainer}>
                <h5 className={style.loginTitle}>Enter Admin ID</h5>
                <Container className={style.loginContent}>
                    <input className={style.loginText} type='text' value={adminid} onChange={(e) => setAdminId(e.target.value)}></input>
                    <button onClick={() => adminlogin(adminid)} className={style.button}>Admin Login</button>
                </Container>
            </Container>
            {/* <div>
                <h3>Enter Admin ID</h3>
                <input className={style.loginText} type='text' value={adminid} onChange={(e) => setAdminId(e.target.value)}></input>
                <button onClick={() => adminlogin(adminid)} className={style.button}>Admin Login</button>
            </div> */}
            {users.is_admin ? (
                <>
                    <Link href="/admin" style={{'text-decoration':'none'}}><button className={style.proceedButton}>Procced</button></Link><br></br>
                </>
            ) : (
                <Container>
                    <h5 className={style.checkTitle}>You are not admin</h5>
                </Container>
            )}
        </>
    )
}

export default Admin