import Head from 'next/head'
import { useState } from 'react'


function Admin() {
  const [user, setUser] = useState('')
  const [users, setUsers] = useState([])

  const getusers = async () => {
    const s = process.env.BASE_FETCH_URL
    const res = await fetch('http://localhost:3000/api/getuserlist')
    const data = await res.json()
    setUsers(data)
  }

  const adduser = async () => {
    const s = process.env.BASE_FETCH_URL
    const res = await fetch('http://localhost:3000/api/insertuser', {
      method: 'POST',
      body: JSON.stringify({ user }),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    const data = await res.json()
    getusers()
  }

  const deleteuser = async name => {
    const s = process.env.BASE_FETCH_URL
    const res = await fetch(`http://localhost:3000/api/deleteuser/${name}`, {
      method: 'DELETE',
    })
    const data = await res.json()
    getusers()
  }

  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is Adminpage</h1>
      </div>
      <div>
        <h1>Add User</h1>
        <h2>Please Input User Details</h2>
        <input type='text' value={user} onChange={(e) => setUser(e.target.value)}></input>
        <button onClick={adduser}>Add User</button>
        <h2>User List</h2>
        <button onClick={getusers}>Get User List</button>
        {
          users.map((user) => {
            return (
              <div key={user._id}>
                {user.name}
                <button onClick={() => deleteuser(user.name)}>
                  Delete User
                </button>
              </div>
            )
          })
        }
      </div>
    </>
  )
}

export default Admin