import Head from 'next/head'
import { useState, useEffect } from 'react'
import Link from 'next/link';
import { Container } from 'react-bootstrap';
import style from '../styles/Admin.module.css'
import '../public/cancelLogo.png'
import '../public/okLogo.png'
import Image from 'react-bootstrap';


function Admin() {
  const [user, setUser] = useState('')
  const [users, setUsers] = useState([])
  const [isloggedin, setIsLoggedIn] = useState(false)
  useEffect(() => {
    checkifadmin()
  }, []);

  const checkifadmin = async () => {
    const loggedInUser = localStorage.getItem("user");
    const resh = await fetch(`/api/checkadmin/${loggedInUser}`)
    const data = await resh.json()
    if (data.is_admin) {
      setIsLoggedIn(true)
    }
  }
  const getusers = async () => {
    const s = process.env.BASE_FETCH_URL
    const res = await fetch('/api/getuserlist')
    const data = await res.json()
    setUsers(data)
  }

  const adduser = async () => {
    const s = process.env.BASE_FETCH_URL
    const admin = localStorage.getItem('user')
    const res = await fetch('/api/insertuser', {
      method: 'POST',
      body: JSON.stringify({ user, admin }),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    const data = await res.json()
    getusers()
  }

  const deleteuser = async name => {
    const s = process.env.BASE_FETCH_URL
    const admin = localStorage.getItem('user')
    const res = await fetch('/api/deleteuser', {
      method: 'POST',
      body: JSON.stringify({ name, admin }),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    const data = await res.json()
    getusers()
  }

  const logout = async name => {
    const loggedInUser = localStorage.removeItem('user');

  }

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"/>
      </Head>
      <Container>
          <h1 className={style.mainTitle}>Admin Dashboard</h1>
      </Container>
      {isloggedin ? (
        <>
          <Container className={style.mainContainer}>
            <Link href="/adminlogin"><button onClick={logout} className={style.button}>Logout</button></Link>
            <h3 className={style.loginTitle}>Add User</h3>
            <h5 className={style.dataTitle}>Please Input User Details</h5>
            <Container className={style.loginContent}>
                <input className={style.loginText} type='text' value={user} onChange={(e) => setUser(e.target.value.toLowerCase())}></input>
                <button onClick={adduser} className={style.button} >Add User</button>
            </Container>
            <h5 className={style.dataTitle}>User List</h5>
            <button className={style.button} onClick={getusers}>Get User List</button>
            <h5 className={style.dataTitle}>Name | if_submitted | is_Admin</h5>
            <Container>

            </Container>
            <Container className={style.outerBox}>
              {
                users.map((user) => {
                  return (
                    <Container key={user._id} className={style.innerBox}>
                      <h5 className={style.boxTitle}>{user.name}</h5>
                      {user.if_submitted ?
                      (
                        <p className={style.logo}>&#9989;</p>
                      )
                      : 
                      (
                        <p className={style.logo}>&#10062;</p>
                      )}
                      {user.is_admin ? 
                      (
                        <h5 className={style.boxTitle}>It is Admin</h5>
                      )
                      : 
                      (
                        <button className={style.deletebutton} onClick={() => {
                          const confirmBox = window.confirm(
                            "Do you really want to delete this Crumb?"
                          )
                          if (confirmBox === true) {
                            deleteuser(user.name)
                          }
                        }}>
                          Delete User
                        </button>
                      )}
                    </Container>
                  )
                })
              }
            </Container>
          </Container>
        </>
      ) : (
        <Container>
            <h5 className={style.checkTitle}>You are not admin</h5>
        </Container>
      )
      }
    </>
  )
}

export default Admin