import Head from 'next/head'
import Link from 'next/link'

export default function feedback() {
  return (
    <>
      <Head>
        <title>FEEDBACK</title>
        <div>
        <p><h1><b>Thank you for voting!</b></h1></p>
            </div>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is Feedback page</h1>
      </div>
    </>
  )
}
