// import redirect from 'nextjs-redirect'
// export default redirect('https://docs.google.com/forms/d/e/1FAIpQLSc5bZBUMK98bxt_P92EHSularg0bo6Y1eWS4jniSZfgVxpRmg/viewform?usp=sf_link')

import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

export default function feedback() {
  return (
    <>
      <Head>
        <title>Feedback</title>
        <div>
        <p><h1><b>Thank you for voting!</b></h1></p>
            </div>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is Feedback page</h1>
      </div>
    </>
  )
}
