import Head from 'next/head'
import Link from 'next/link'
import HomeLogo from '../Components/HomeLogo'
import HomeContent from '../Components/HomeContent'
import Container from 'react-bootstrap/Container';
import 'bootstrap/dist/css/bootstrap.min.css';
import style from '../styles/Index.module.css';

export default function Home() {
  return (
    <Container fluid className={style.mainBody}>
      <Head>
        <title>Picsoreel 2k23!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Niconne&display=swap" rel="stylesheet" />
      </Head>
      {/* <div style={{margin:"auto", width:"70%"}}> */}
        {/* <h1>This is Homepage</h1> */}
        {/* <Link href="/adminlogin"><button>Admin</button></Link><br></br> */}
        {/* <Link href="/login"><button>Voter Login</button></Link> */}
      {/* </div> */}
      <Container className={style.mainContainer}>
        <HomeLogo />
        <HomeContent />
      </Container>
    </Container>
  )
}