import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'

export default function Admin() {
  const [users, setUsers] = useState([])
  const [userid, setUserId] = useState('')
  const userlogin = async userid => {
    const s = process.env.BASE_FETCH_URL
    const res = await fetch(`http://localhost:3000/api/checkadmin/${userid}`)
    const data = await res.json()
    setUsers(data)
    localStorage.setItem('user', data.name)
  }
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is Instruction Page</h1>
        <div>
          <h3>Enter User ID (eg:c2k....)</h3>
          <input type='text' value={userid} onChange={(e) => setUserId(e.target.value)}></input>
          <Link href="/scanner"><button onClick={() => userlogin(userid)}>User Login</button></Link>
        </div>
      </div>
      {/* {users.name ? (
        <>
          <Link href="/scanner"><button>Procced to Scan</button></Link><br></br>
        </>
      ) : (
        <div>
          You are not Logged in
        </div>
      )} */}
      {/* <Link href="/votingpage"><button>Next</button></Link><br></br> */}
    </>
  )
}
