import Head from 'next/head'
import Link from 'next/link'

export default function Admin() {
  return (
    <>
      <Head>
        <title>My Votes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is My Votes Page</h1>
        <Link href="/feedback"><button>Final Submit</button></Link><br></br>

      </div>
    </>
  )
}
