import Head from "next/head"
import { useState, useEffect} from 'react'
import { useRouter } from "next/router";


export default function Scanner() {
    const [images, setImages] = useState([])
    const getimage = async locid => {
        const s = process.env.BASE_FETCH_URL
        const res = await fetch(`http://localhost:3000/api/getimage/${locid}`)
        const data = await res.json()
        // console.log(data)
        setImages(data)
    }
    var router = useRouter();
    var id = router.query["id"];
    
    console.log(id)
    if (id === "No number" || (id.slice(0, 1) !== "p" && id.slice(0, 1) !== "s")) {

    }
    else {
        getimage(id);
    }
    return (
        <>
            <Head>
                <title>Image Display</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>This is image display page</h1>
                {/* <button onClick={() => getimage(id)}>Load Image</button> */}

                <div key={images.image_id}>
                    {images.name} | {images.class} | {images.vote}
                </div>
                <img src={images.url}></img>


            </div>
        </>

    )
}