import Head from 'next/head'
import Link from 'next/link'

export default function Admin() {
  return (
    <>
      <Head>
        <title>Voting Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is Votingpage</h1>
        <Link href="/scanner"><button>Scan to vote</button></Link><br></br>
        <Link href="/myvotes"><button>My votes</button></Link>
      </div>
    </>
  )
}
