import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react'

export default function Wishlist() {
  const [isloggedin, setIsLoggedIn] = useState(false)
  const checkifuser = async () => {
    const loggedInUser = localStorage.getItem("user");
    const resh = await fetch(`http://localhost:3000/api/checkadmin/${loggedInUser}`)
    const data = await resh.json()
    if (data.name !== "notuser") {
      setIsLoggedIn(true)
    }
  }

  const logout = async name => {
    localStorage.removeItem('user');
  }

  //displaying all the images with category painting from atlas
  const [paintings, setPainting] = useState([])
  const [photographys, setPhotography] = useState([])
  const [digitalarts, setDigitalart] = useState([])
  const [themes, setTheme] = useState([])

  const getcat = async cate => {
    // console.log(loggedInUser)
    const loggedInUser = localStorage.getItem('user')
    const res = await fetch('http://localhost:3000/api/getWishlist', {
      method: 'POST',
      body: JSON.stringify({ category: cate, username: loggedInUser }),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    const data = await res.json()
    return data;
  }

  const deletevote = async imgid => {
    const loggedInUser = localStorage.getItem('user')
    const res = await fetch('http://localhost:3000/api/deletevote', {
      method: 'POST',
      body: JSON.stringify({ username: loggedInUser, image_id: imgid }),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    loadallimages();
  }

  function getCount() {
    var votecount = paintings.length + photographys.length + digitalarts.length + themes.length;
    return votecount;
  }


  const submitvotes = async () => {
    const loggedInUser = localStorage.getItem('user')
    const res = await fetch('http://localhost:3000/api/submitvotes', {
      method: 'POST',
      body: JSON.stringify({username: loggedInUser}),
      headers: {
        'Content-Type': 'application/JSON'
      }
    })
    const data = await res.json()
  }

  const loadallimages = async () => {
    setPainting(await getcat("painting"));
    setPhotography(await getcat("photo"));
    setTheme(await getcat("theme"));
    setDigitalart(await getcat("digital"));

    // getcat("painting");
    // getcat("photo");
    // getcat("theme");
    // getcat("digital");
  }

  //starting state of the page
  useEffect(() => {
    loadallimages(),
      checkifuser()
  }, []);

  return (
    <>
      <Head>
        <title>My Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is My Wishlists Page</h1>
        <Link href="/scanner"><button>Scan More</button></Link><br></br>
        <div>
          <div>
            {/* <button onClick={() => loadallimages()}>Show all entries</button> */}
            <p>Painting/Sketches |||| No. of Votes Remaining: {2 - paintings.length} </p>
            {
              paintings.map((painting) => {
                return (
                  <>
                    <div key={painting.image_id}>
                      {painting.name} | {painting.category} | {painting.class}
                    </div>
                    <img src={painting.url}></img>
                    <button onClick={() => deletevote(painting.image_id)}>Delete</button>
                  </>
                )
              })
            }
          </div>
          <div>
            <p>Photography |||| No. of Votes Remaining: {2 - photographys.length}</p>
            {
              photographys.map((photograph) => {
                return (
                  <>
                    <div key={photograph.image_id}>
                      {photograph.name} | {photograph.category} | {photograph.class}
                    </div>
                    <img src={photograph.url}></img>
                    <button onClick={() => deletevote(photograph.image_id)}>Delete</button>
                  </>
                )
              })
            }
          </div>
          <div>
            <p>Digital Art |||| No. of Votes Remaining: {2 - digitalarts.length} </p>
            {
              digitalarts.map((dart) => {
                return (
                  <>
                    <div key={dart.image_id}>
                      {dart.name} | {dart.category} | {dart.class}
                    </div>
                    <img src={dart.url}></img>
                    <button onClick={() => deletevote(dart.image_id)}>Delete</button>
                  </>
                )
              })
            }
          </div>
          <div>
            <p>Theme |||| No. of Votes Remaining: {2 - themes.length} </p>
            {
              themes.map((theme) => {
                return (
                  <>
                    <div key={theme.image_id}>
                      {theme.name} | {theme.category} | {theme.class}
                    </div>
                    <img src={theme.url}></img>
                    <button onClick={() => deletevote(theme.image_id)}>Delete</button>
                  </>
                )
              })
            }
          </div>
        </div>
        <div>
          {getCount() === 8 ?
            (
              <><Link href="/feedback"><button onClick={() => submitvotes()}>Final Submit</button></Link><br></br></>
            ) :
            (<><button onClick={() => alert("Please enter 2 votes for each category")}>Final Submit</button></>)}
        </div>
      </div>
    </>
  )
}